<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE MIDOLAR [
<!ELEMENT MIDOLAR (VALORCOMPRA,VALORVENTA,HORA,FECHA,HORAUNIX)>
<!ELEMENT VALORCOMPRA (#PCDATA)>
<!ELEMENT VALORVENTA (#PCDATA)>
<!ELEMENT HORA (#PCDATA)>
<!ELEMENT FECHA (#PCDATA)>
<!ELEMENT HORAUNIX (#PCDATA)>]>
<MIDOLAR>
  <VALORCOMPRA></VALORCOMPRA>
  <VALORVENTA></VALORVENTA>
  <HORA>1:00:03</HORA>
  <FECHA>2011-05-15</FECHA>
  <HORAUNIX>1305432003</HORAUNIX>
</MIDOLAR>
